name: myenv
channels:
  - conda-forge
dependencies:
  - ml-notebook==2022.02.04
  - xarray
  - netcdf4
  - aiohttp
  - gcsfs
  - intake
  - intake-xarray
  - zarr
  - matplotlib
  - cartopy
  - cmocean
  - hvplot
  - seaborn
  - scikit-learn
  - dask-ml
  - argopy